<?php
if(!defined('ABSPATH'))exit;
class Ostadi_Elements_Gutenberg{
 public function __construct(){add_action('init',[$this,'register']);}
 public function register(){
  wp_register_script('ostadi-blocks-1',OSTADI_ELEMENTS_URL.'assets/js/blocks.js',['wp-blocks','wp-element','wp-i18n','wp-block-editor'],OSTADI_ELEMENTS_VERSION,true);
  $defs=['article-grid'=>['مقالات','post'],'video-grid'=>['ویدئوها','ostadi_video'],'podcast-grid'=>['پادکست‌ها','ostadi_podcast'],'article-showcase'=>['ویترین مقالات','post']];
  foreach($defs as $slug=>$def) register_block_type('ostadi/'.$slug,['api_version'=>2,'editor_script'=>'ostadi-blocks-1','attributes'=>['count'=>['type'=>'number','default'=>6],'title'=>['type'=>'string','default'=>$def[0]]],'render_callback'=>function($a)use($def){return Ostadi_Elements_Renderer::grid($def[1],max(1,min(12,(int)($a['count']??6))),sanitize_text_field($a['title']??$def[0]),$def[1]);}]);
 }
}
class Ostadi_Elements_Renderer{
 public static function grid($type,$count,$title,$kind){$q=new WP_Query(['post_type'=>$type,'post_status'=>'publish','posts_per_page'=>$count,'no_found_rows'=>true]);ob_start();?><section class="ostadi-section ostadi-section--<?php echo esc_attr($kind);?>" dir="rtl"><div class="ostadi-section-head"><div><span class="ostadi-eyebrow"><?php echo esc_html($kind==='ostadi_video'?'ویدئوهای آموزشی':($kind==='ostadi_podcast'?'پادکست‌های آموزشی':'مقالات آموزشی'));?></span><h2><?php echo esc_html($title);?></h2></div><a href="<?php echo esc_url(get_post_type_archive_link($type));?>">مشاهده همه ←</a></div><div class="ostadi-grid"><?php while($q->have_posts()):$q->the_post();$id=get_the_ID();$img=get_the_post_thumbnail_url($id,'large');$tax=$kind==='ostadi_video'?'ostadi_video_category':($kind==='ostadi_podcast'?'ostadi_podcast_category':'category');$terms=get_the_terms($id,$tax);$cat=(!is_wp_error($terms)&&$terms)?$terms[0]->name:'آموزش';$dur=get_post_meta($id,'_ostadi_duration',true);?><article class="ostadi-card"><a class="ostadi-card__media" href="<?php the_permalink();?>"><?php if($img):?><img src="<?php echo esc_url($img);?>" alt="<?php echo esc_attr(get_the_title());?>"><?php else:?><span class="ostadi-card__placeholder"><?php echo $kind==='ostadi_video'?'▶':($kind==='ostadi_podcast'?'🎙':'✦');?></span><?php endif;?><?php if($kind!=='post'):?><span class="ostadi-play">▶</span><?php endif;?><span class="ostadi-badge"><?php echo esc_html($cat);?></span></a><div class="ostadi-card__body"><h3><a href="<?php the_permalink();?>"><?php the_title();?></a></h3><p><?php echo esc_html(wp_trim_words(get_the_excerpt(),16));?></p><div class="ostadi-meta"><span><?php echo esc_html(get_the_date());?></span><?php if($dur):?><span><?php echo esc_html($dur);?></span><?php endif;?></div></div></article><?php endwhile;wp_reset_postdata();?></div></section><?php return ob_get_clean();}
}
