<?php
if (!defined('ABSPATH')) exit;
class Ostadi_Elements_Content_Types {
 public function __construct(){add_action('init',[$this,'register']);add_action('add_meta_boxes',[$this,'boxes']);add_action('save_post_ostadi_video',[$this,'save_video']);add_action('save_post_ostadi_podcast',[$this,'save_podcast']);}
 public function register(){
  register_post_type('ostadi_video',['labels'=>['name'=>'ویدئوها','singular_name'=>'ویدئو','add_new'=>'افزودن ویدئو','add_new_item'=>'افزودن ویدئوی جدید','edit_item'=>'ویرایش ویدئو','menu_name'=>'ویدئوها'],'public'=>true,'show_in_rest'=>true,'menu_icon'=>'dashicons-video-alt3','supports'=>['title','editor','thumbnail','excerpt','author'],'has_archive'=>true,'rewrite'=>['slug'=>'videos','with_front'=>false]]);
  register_taxonomy('ostadi_video_category','ostadi_video',['labels'=>['name'=>'دسته‌بندی ویدئو','singular_name'=>'دسته‌بندی ویدئو'],'public'=>true,'show_in_rest'=>true,'hierarchical'=>true,'rewrite'=>['slug'=>'video-category']]);
  register_taxonomy('ostadi_video_tag','ostadi_video',['labels'=>['name'=>'برچسب ویدئو','singular_name'=>'برچسب ویدئو'],'public'=>true,'show_in_rest'=>true,'hierarchical'=>false,'rewrite'=>['slug'=>'video-tag']]);
  register_post_type('ostadi_podcast',['labels'=>['name'=>'پادکست‌ها','singular_name'=>'پادکست','add_new'=>'افزودن پادکست','add_new_item'=>'افزودن پادکست جدید','edit_item'=>'ویرایش پادکست','menu_name'=>'پادکست‌ها'],'public'=>true,'show_in_rest'=>true,'menu_icon'=>'dashicons-microphone','supports'=>['title','editor','thumbnail','excerpt','author'],'has_archive'=>true,'rewrite'=>['slug'=>'podcasts','with_front'=>false]]);
  register_taxonomy('ostadi_podcast_category','ostadi_podcast',['labels'=>['name'=>'دسته‌بندی پادکست','singular_name'=>'دسته‌بندی پادکست'],'public'=>true,'show_in_rest'=>true,'hierarchical'=>true,'rewrite'=>['slug'=>'podcast-category']]);
  register_taxonomy('ostadi_podcast_tag','ostadi_podcast',['labels'=>['name'=>'برچسب پادکست','singular_name'=>'برچسب پادکست'],'public'=>true,'show_in_rest'=>true,'hierarchical'=>false,'rewrite'=>['slug'=>'podcast-tag']]);
 }
 public function boxes(){add_meta_box('ostadi_video_meta','اطلاعات ویدئو',[$this,'video_box'],'ostadi_video','normal','high');add_meta_box('ostadi_podcast_meta','اطلاعات پادکست',[$this,'podcast_box'],'ostadi_podcast','normal','high');}
 public function video_box($p){wp_nonce_field('ostadi_video','ostadi_video_nonce');$u=get_post_meta($p->ID,'_ostadi_video_url',true);$d=get_post_meta($p->ID,'_ostadi_duration',true);echo '<p><b>URL ویدئو</b><input class="widefat" name="ostadi_video_url" value="'.esc_attr($u).'" placeholder="https://..."></p><p><b>مدت</b><input class="regular-text" name="ostadi_duration" value="'.esc_attr($d).'" placeholder="12:40"></p>';}
 public function podcast_box($p){wp_nonce_field('ostadi_podcast','ostadi_podcast_nonce');$u=get_post_meta($p->ID,'_ostadi_audio_url',true);$d=get_post_meta($p->ID,'_ostadi_duration',true);echo '<p><b>URL فایل صوتی</b><input class="widefat" name="ostadi_audio_url" value="'.esc_attr($u).'" placeholder="https://...mp3"></p><p><b>مدت</b><input class="regular-text" name="ostadi_podcast_duration" value="'.esc_attr($d).'" placeholder="28:35"></p>';}
 public function save_video($id){if(!isset($_POST['ostadi_video_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['ostadi_video_nonce'])),'ostadi_video')||defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE||!current_user_can('edit_post',$id))return;update_post_meta($id,'_ostadi_video_url',esc_url_raw(wp_unslash($_POST['ostadi_video_url']??'')));update_post_meta($id,'_ostadi_duration',sanitize_text_field(wp_unslash($_POST['ostadi_duration']??'')));}
 public function save_podcast($id){if(!isset($_POST['ostadi_podcast_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['ostadi_podcast_nonce'])),'ostadi_podcast')||defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE||!current_user_can('edit_post',$id))return;update_post_meta($id,'_ostadi_audio_url',esc_url_raw(wp_unslash($_POST['ostadi_audio_url']??'')));update_post_meta($id,'_ostadi_duration',sanitize_text_field(wp_unslash($_POST['ostadi_podcast_duration']??'')));}
}
