<?php
if(!defined('ABSPATH'))exit;
abstract class Ostadi_Elementor_Media_Grid extends \Elementor\Widget_Base{
 abstract protected function post_type(); abstract protected function kind();
 public function get_icon(){return 'eicon-posts-grid';} public function get_categories(){return ['ostadi-1'];}
 protected function register_controls(){ $this->start_controls_section('content',['label'=>'محتوا']);$this->add_control('title',['label'=>'عنوان','type'=>\Elementor\Controls_Manager::TEXT,'default'=>$this->kind()==='video'?'ویدئوهای آموزشی':'پادکست‌های آموزشی']);$this->add_control('count',['label'=>'تعداد','type'=>\Elementor\Controls_Manager::NUMBER,'min'=>1,'max'=>12,'default'=>4]);$this->end_controls_section(); }
 protected function render(){ $s=$this->get_settings_for_display();$type=$this->post_type();$kind=$this->kind();$q=new WP_Query(['post_type'=>$type,'post_status'=>'publish','posts_per_page'=>max(1,min(12,(int)$s['count'])),'no_found_rows'=>true]);echo '<section class="ostadi-section ostadi-section--'.esc_attr($type).'" dir="rtl"><div class="ostadi-section-head"><h2>'.esc_html($s['title']).'</h2><a href="'.esc_url(get_post_type_archive_link($type)).'">مشاهده همه ←</a></div><div class="ostadi-grid">';while($q->have_posts()){$q->the_post();$id=get_the_ID();$img=get_the_post_thumbnail_url($id,'large');$dur=get_post_meta($id,'_ostadi_duration',true);$url=$kind==='podcast'?get_post_meta($id,'_ostadi_audio_url',true):get_post_meta($id,'_ostadi_video_url',true);echo '<article class="ostadi-card"><a class="ostadi-card__media" href="'.esc_url(get_permalink()).'">';if($img)echo '<img src="'.esc_url($img).'" alt="'.esc_attr(get_the_title()).'">';else echo '<span class="ostadi-card__placeholder">'.($kind==='video'?'▶':'🎙').'</span>';echo '<span class="ostadi-play">▶</span><span class="ostadi-badge">'.($kind==='video'?'ویدئو':'پادکست').'</span></a><div class="ostadi-card__body"><h3><a href="'.esc_url(get_permalink()).'">'.esc_html(get_the_title()).'</a></h3><p>'.esc_html(wp_trim_words(get_the_excerpt(),16)).'</p>';if($kind==='podcast'&&$url)echo '<button class="ostadi-button" data-ostadi-audio="'.esc_url($url).'">پخش پادکست</button>';echo '<div class="ostadi-meta"><span>'.esc_html(get_the_date()).'</span>'.($dur?'<span>'.esc_html($dur).'</span>':'').'</div></div></article>';}wp_reset_postdata();echo '</div></section>';}
}
class Ostadi_Elementor_Video_Grid extends Ostadi_Elementor_Media_Grid{public function get_name(){return 'ostadi-video-grid';}public function get_title(){return 'شبکه ویدئوهای استادی';}protected function post_type(){return 'ostadi_video';}protected function kind(){return 'video';}}
class Ostadi_Elementor_Podcast_Grid extends Ostadi_Elementor_Media_Grid{public function get_name(){return 'ostadi-podcast-grid';}public function get_title(){return 'شبکه پادکست‌های استادی';}protected function post_type(){return 'ostadi_podcast';}protected function kind(){return 'podcast';}}
